config/routes.rb
Rails.application.routes.draw do
  root to: 'tweets#index'
  devise_for :users
  resources :tweets, only: %i[index create edit update destroy] do
    resource :likes, only: %i[create destroy]
  end

  namespace :tweets do
    resources :mines, only: %i[index]
    resources :mylikes, only: %i[index]
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :tweet
end

app/models/tweet.rb
class Tweet < ApplicationRecord
  belongs_to :user
  has_many :likes, dependent: :destroy

  validates :content, presence: true, length:{maximum: 140}
end

app/models/user.rb
class User < ApplicationRecord
  has_many :tweets, dependent: :destroy
  has_many :likes, dependent: :destroy
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :name, presence: true, length:{maximum: 20}, uniqueness: true, on: :create
  validates :email, presence: true, uniqueness: true
  validates :encrypted_password, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?
  before_action :authenticate_user!
  before_action :set_basic_auth

  protected
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end

  def set_basic_auth
    return unless ENV['RAILS_ENV'] == 'production'
    authenticate_or_request_with_http_basic do |name, password|
      name == ENV['BASIC_AUTH_NAME'] && password == ENV['BASIC_AUTH_PASSWORD']
    end
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  before_action :set_tweet, only: %i[ create destroy ]

  def create
    @like = current_user.likes.build(tweet: @tweet)
    @like.save
  end

  def destroy
    @like = current_user.likes.find_by(tweet: @tweet)
    @like.destroy
  end

  private
    def set_tweet
      @tweet = Tweet.find(params[:tweet_id])
    end
end

app/controllers/tweets/likes_controller.rb
class Tweets::LikesController < ApplicationController
  def index
    @tweets = Tweet.where(id: current_user.likes.map(&:tweet_id)).order(created_at: :desc).page(params[:page]).per(15)
  end
end

app/controllers/tweets/mines_controller.rb
class Tweets::MinesController < ApplicationController
  def index
    @tweets = current_user.tweets.order(created_at: :desc).page(params[:page]).per(15)
  end
end

app/controllers/tweets/mylikes_controller.rb
class Tweets::MylikesController < ApplicationController
  def index
    @tweets = Tweet.where(id: current_user.likes.map(&:tweet_id)).order(created_at: :desc).page(params[:page]).per(15)
  end
end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
  before_action :set_tweet, only: %i[ edit update destroy ]

  #GET /tweets  prefix:tweets
  def index
    @tweets = Tweet.order(created_at: :desc).page(params[:page]).per(15)
    @tweet = Tweet.new
  end

  #POST /tweets  prefix:tweets
  def create
    @tweet = current_user.tweets.build(tweet_params)

    if @tweet.save
      redirect_to tweets_path
    else
      render :index, status: :unprocessable_entity
    end
  end

  #GET /tweets/id/edit  prefix:edit_tweet
  def edit
  end

  #PATCH or PUT  /tweets/id  prefix:tweet
  def update
    if @tweet.update(tweet_params)
      redirect_to request.referer, notice: 'ツイートが編集されました'
    else
      render :edit, status: :unprocessable_entity
    end
  end

  #DELETE  /tweets/id  prefix:tweet
  def destroy
    @tweet.destroy
    redirect_to tweets_path
  end

  private
    def set_tweet
      @tweet = Tweet.find(params[:id])
    end

    def tweet_params
      params.require(:tweet).permit(:content)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/tweets_helper.rb
module TweetsHelper
end

app/views/layouts/_like.html.erb
<% if current_user.likes.find_by(tweet: tweet) %>
  <%=link_to tweet_likes_path(tweet), method: :delete, remote: true do %>
    <i class="fas fa-heart fa-lg" style="color: red;"></i>
  <% end %>
<% else %>
  <%= link_to tweet_likes_path(tweet), method: :post, remote: true do %>
    <i class="far fa-heart fa-lg" style="color: red;"></i>
  <% end %>
<% end %>

app/views/layouts/_nav.html.erb
<div class="sp"><!-- スマホ用ナビゲーションバー -->
  <div class="d-flex justify-content-between border-bottom">
    <!-- ナビゲーションメニュー -->
    <div class="nav-sp">
      <ul class="nav-menu nav-menu-sp fa-ul">
        <li><%= link_to tweets_path do %><i class="fas fa-li fa-home fa-2x"></i><% end %></li>
        <li><%= link_to tweets_mylikes_path do %><i class="far fa-li fa-heart fa-2x"></i><% end %></li>
        <li><%= link_to tweets_mines_path do %><i class="fab fa-li fa-twitter fa-2x"></i><% end %></li>
      </ul>
    </div>

    <!-- ログアウトボタン -->
    <div class="logout-sp">
      <%= link_to 'ログアウト', destroy_user_session_path, method: :delete, class: "btn" %>
    </div>
  </div>
</div><!--.sp-->

<!-- PC -->
<!-- ログアウトボタン -->
<div class="logout d-flex justify-content-end">
  <%= link_to 'ログアウト', destroy_user_session_path, method: :delete, class: "btn" %>
</div>

<!-- ナビゲーションメニュー -->
<div class="col-md-3 mt-md-3">
  <div class="nav-pc">
    <ul class="nav-menu fa-ul">
      <li>
        <%= link_to tweets_path do %>
          <i class="fas fa-li fa-home fa-lg"></i><span>ホーム</span>
        <% end %>
      </li>
      <li>
        <%= link_to tweets_mylikes_path do %>
          <i class="far fa-li fa-heart fa-lg"></i><span>LIKES</span>
        <% end %>
      </li>
      <li>
        <%= link_to tweets_mines_path do%>
          <i class="fab fa-li fa-twitter fa-lg"></i><span>マイツイート</span>
        <% end %>
      </li>
    </ul>
  </div>
</div><!-- ナビメニュー -->

app/views/layouts/_tweetboard.html.erb
<!--タイムライン-->
<table class="table table-borderless">
  <% @tweets.each do |tweet|%>
    <tr><th colspan="4"><%= tweet.user&.name %></th></tr>
    <tr><td colspan="4"><%= simple_format(h(tweet.content)) %></td></tr>

    <tr class="links border-bottom">
      <!--❤️-->
      <td id="<%= dom_id(tweet) %>">
        <%= render 'layouts/like', tweet: tweet %>
      </td>

      <td><!--✏️編集-->
        <% if user_signed_in? && current_user.id == tweet.user_id %>
          <%= link_to edit_tweet_path(tweet) do %>
            <i class="fas fa-pencil-alt"></i><span>編集</span>
          <% end %>
        <% end %>
      </td>

      <td><!--✖️削除-->
        <% if user_signed_in? && current_user.id == tweet.user_id %>
          <%= link_to tweet, method: :delete, data: { confirm: '削除してもよろしいですか？' } do %>
            <i class="fas fa-times"></i><span>削除</span>
          <% end %>
        <% end %>
      </td>

      <td><%= l tweet.created_at, format: :long%></td><!--日付-->
    </tr><!-- .links -->
  <% end %>
</table>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Tweetboard</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <script src="https://kit.fontawesome.com/2d6f3622dc.js" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.4/css/all.css">
  </head>

  <body>
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/likes/create.js.erb
document.querySelector("#tweet_<%= @tweet.id %>").innerHTML = "<%= j(render('/layouts/like', tweet: @tweet)) %>";

app/views/likes/destroy.js.erb
document.querySelector("#tweet_<%= @tweet.id %>").innerHTML = "<%= j(render('/layouts/like', tweet: @tweet)) %>";

app/views/tweets/edit.html.erb
<div class="row">
  <div class="col-md-8 offset-md-2">
    <div class="card">
      <div class="card-body">
        <h2>ツイート編集</h2>
        <p class="h5 text-secondary mt-5 mb-4"><%= current_user&.name %></p>
        <p class="d-flex justify-content-center" style="color: rgb(243, 53, 148);"><%= notice %></p>

        <%= form_with model: @tweet do |form| %>
          <div class="form-group">
            <%= form.text_area :content, class: "form-control form-control-lg" %>
          </div>
          <div class="edit_tweet_actions d-flex justify-content-end">
            <%= form.submit '編 集', class: 'btn' %>
          </div>
        <% end %>

        <%= link_to 'ホームへ', tweets_path, class: 'small text-decoration-none text-info' %>
        <p><%= link_to 'マイツイートへ', tweets_mines_path, class: 'small text-decoration-none text-info' %></p>

      </div>
    </div>
  </div>
</div>

app/views/tweets/index.html.erb
<div class="row mt-1 mb-3 px-sm-3 border">
  <!-- ログアウトボタン・ナビゲーションメニュー -->
  <%= render 'layouts/nav' %>

  <!--ツイートフォーム・タイムライン-->
  <div class="col-xs-12 col-md-9">
    <p style="color: rgb(243, 53, 148);"><%= notice %></p>
    <strong>ホーム</strong>&emsp;こんにちは <%= current_user&.name %>さん

      <!--ツイート投稿フォーム・ボタン-->
      <%= form_with class:"mt-3", model: @tweet do |form| %>
        <div class="form-group">
          <%= form.text_area :content, class: "form-control form-control-lg", placeholder: 'いまどうしてる？'%>
          <div class="d-flex justify-content-end">
            <%= form.submit 'ツイート', class: 'btn' %>
          </div>
        </div>
      <% end %>

      <!--タイムライン-->
      <%= render 'layouts/tweetboard' %>

  </div>

  <div id="page_top"><%= link_to "",tweets_path %></div>

  <%= paginate @tweets %>
</div>

app/views/tweets/mines/index.html.erb
<div class="row mt-1 mb-3 px-sm-3 border">
  <%= render 'layouts/nav' %>

  <div class="col-xs-12 col-md-9 mt-md-3">
    <strong class="p-2">マイツイート</strong>

    <div class="tweetboard mt-5">
      <%= render 'layouts/tweetboard' %>
    </div>

    <div id="page_top"><%= link_to "",tweets_mines_path %></div>
  </div>

  <%= paginate @tweets %>
</div>

app/views/tweets/mylikes/index.html.erb
<div class="row mt-1 mb-3 px-sm-3 border">
  <!-- ログアウトボタン・ナビゲーションメニュー -->
  <%= render 'layouts/nav' %>

  <div class="col-md-9 col-xs-12 mt-md-3">
    <strong>LIKES</strong>

    <!--LIKES一覧-->
    <div class="mt-4">
      <%= render 'layouts/tweetboard' %>
    </div>
  </div>

  <div id="page_top"><%= link_to "",tweets_mylikes_path %></div>

  <%= paginate @tweets %>
</div>

app/views/tweets/show.html.erb
<h1>Tweets#show</h1>
<p>Find me in app/views/tweets/show.html.erb</p>